/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg20424073_lab2;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

class MyClass implements ActionListener {
    
    MyClass() {
    }

    public void actionPerformed(ActionEvent e) {
        String strActionCommand = e.getActionCommand();
        if (strActionCommand.equals("jbt1")) {
            
            
        }
        if (strActionCommand.equals("jbt2")) {
            
        }
        if (strActionCommand.equals("jbt3")) {
            
        }
        if (strActionCommand.equals("jbt4")) {

        }
    }
}
public class MenuMain extends javax.swing.JFrame {

    /**
     * Creates new form MenuMain
     */
    private JButton jbt1;
    private JButton jbt2;
    private JButton jbt3;
    private JButton jbt4;
    private JButton jbt5;
    private JButton jbt6;
    private JButton jbt7;
    private JButton jbt8;    
    public MenuMain() {
        initComponents();
        this.Myinit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public void Myinit(){
        MyClass mc = new MyClass();
        this.jbt1 = new JButton();
        this.jbt1.setText("Search Slang");
        this.jbt1.setBounds(50,100,150, 40);
        this.add(this.jbt1);
        this.jbt1.setActionCommand("jbt1");
        this.jbt1.addActionListener(mc);
        
        this.jbt2 = new JButton();
        this.jbt2.setText("Search definition");
        this.jbt2.setBounds(200,100,150, 40); 
        this.add(this.jbt2);
        this.jbt2.setActionCommand("jbt2");
        this.jbt2.addActionListener(mc);
        
        
        this.jbt3 = new JButton();
        this.jbt3.setText("Hitory");
        this.jbt3.setBounds(350,100,150, 40); 
        this.add(this.jbt3);
        this.jbt3.setActionCommand("jbt3");
        this.jbt3.addActionListener(mc);
        
        this.jbt4 = new JButton();
        this.jbt4.setText("Add, Edit, Delete");
        this.jbt4.setBounds(200,170,150,40); 
        this.add(this.jbt4);
        this.jbt4.setActionCommand("jbt4");
        this.jbt4.addActionListener(mc);
        
        this.jbt5 = new JButton();
        this.jbt5.setText("Reset");
        this.jbt5.setBounds(50,170,150,40); 
        this.add(this.jbt5);
        this.jbt5.setActionCommand("jbt5");
        this.jbt5.addActionListener(mc);
        
        this.jbt6 = new JButton();
        this.jbt6.setText("Ramdom");
        this.jbt6.setBounds(350,170,150,40); 
        this.add(this.jbt6);
        this.jbt6.setActionCommand("jbt6");
        this.jbt6.addActionListener(mc);
        
        this.jbt7 = new JButton();
        this.jbt7.setText("question slang");
        this.jbt7.setBounds(50,240,225,40); 
        this.add(this.jbt7);
        this.jbt7.setActionCommand("jbt7");
        this.jbt7.addActionListener(mc);
        
        this.jbt8 = new JButton();
        this.jbt8.setText("question definition");
        this.jbt8.setBounds(275,240,225,40); 
        this.add(this.jbt8);
        this.jbt8.setActionCommand("jbt8");
        this.jbt8.addActionListener(mc);
        
        
        this.setSize(600, 500);
        this.setTitle("Menu");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);

              
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
